### PR TITLE
Target netstandard2.0 and net45

### PR DESCRIPTION
**Pull request by fjch1997**
**What's in this PR**

Converted all project files to SDK-style format targeting `netstandard2.0;net45;net46;net47`
Updated gitignore with the Visual Studio template

**Breaking changes**
For users of the nuget package, there should be none because net45 is still being targeted.
For people using the source code, the latest Visual Studio 2019 version must be used.
Version is fixed to 3.1.0 because the new format does not support starred version.

**To build nuget packages**

Call msbuild with `-t:pack -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg`

A way to set the version in CI pipeline would be `-p:PackageVersion="3.1.0-CI-$(Build.BuildNumber)"`

### CODE REVIEW

**Comment by stewienj** [comment]
Thanks for this, it's something that's been on my todo list for a while. I seem to be having a problem where the nuget packages are always debug builds despite me specifying Release as the config:

msbuild Swordfish.NET.Collections.sln -t:pack -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -p:Platform="Any CPU" -p:Config="Release"

**Comment by fjch1997** [comment]
Try this `-p:Configuration="Release"`

**Comment by stewienj** [comment]
New packages:
[Swordfish.NET.Collections](https://www.nuget.org/packages/Swordfish.NET.Collections/2.1.0)
[Swordfish.NET](https://www.nuget.org/packages/Swordfish.NET/3.1.0)
[Swordfish.NET.CollectionsV3](https://www.nuget.org/packages/Swordfish.NET.CollectionsV3/3.1.0)

**Comment by stewienj** [comment]
I've merged Swordfish.NET into an auxiliary namespace under Swordfish.NET.CollectionsV3 as my company is moving to using nuget packages and that DLL is going to cause issues.

And I've created a separate workflow for doing releases, vs doing a release on every push. This workflow uses the tag as the minor version numbers for the file version and nuget package version.

[Here's the workflow](https://github.com/stewienj/SwordfishCollections/blob/master/.github/workflows/release.yml)

**Pull request merged**
