### PR TITLE
Nuget package

### PR DESCRIPTION
**Pull request by fjch1997**
### Changes

1. Downgraded Swordfish.NET.CollectionsV3 framework version to 4.5
2. Modified .nuspec files.
3. Calling nuget pack as post-build events.
4. Generate XML documentation under Release_AnyCPU.

### Next step
1. Upload the .nupkg files under Bin\Release_AnyCPU to nuget.org. [Link](https://www.nuget.org/packages/manage/upload)
2. Contact Jojatekok to take down the existing  .
Swordfish.NET Collections (or mark it obsolete or soemthing).

### CODE REVIEW

**Comment by fjch1997** [comment]
I've uploaded the package myself. @stewienj Please let me know if you want to do it under your name and I'll take it down.

**Comment by stewienj** [comment]
@fjch1997 Thanks for that, I've haven't had the chance to look into how to publish a nuget package but you've saved me the trouble. I'm happy for you to have the package under your name if that's no trouble.

**Comment by vslee** [comment]
@fjch1997, could you push a new nuget?

**Comment by fjch1997** [comment]
Yes

**Comment by stewienj** [comment]
Sorry for all the extra commits just when you are doing a nuget release. I decided to try to get github actions to automatically do a build on this repo whenever there is a commit or a pull request. Doing it by trial and error. I think I've got it working properly now.

**Comment by fjch1997** [comment]
@stewienj Great! At one point you should have a nuget.org account. Let me know what your username is so nuget lets you publish under the name Swordfish.NET.CollectionsV3 and Swordfish.NET.Collections

**Comment by stewienj** [comment]
@fjch1997 I've created a nuget.org account, username stewienj. I've also modified assembly.cs to use epoch version numbering, so the versioning will be automatic. And I've separated out the github actions to separate ones for a push or pull-request. Will only publish automatically to nuget on a push to master. It looks like nuget.org still has the old version from 25th July 2017.

Just need to work out that last bit on how to get github to access my nuget account.

**Comment by stewienj** [comment]
I've got github set up to automatically publish to nuget, now all I need is permission on the nuget package,

**Comment by vslee** [comment]
Perhaps it would be better for @fjch1997 to archive his nuget listing and for @stewienj to push a new listing. Thus, it would show the nuget as being published by @stewienj. It was confusing for me at first when I first saw the previous nuget. Took a bit of digging on this page to figure out that it was not posted by an imposter.
Once @stewienj publishes his own nuget, he can still give @fjch1997 permissions to push nugets on his behalf.

**Comment by fjch1997** [comment]
I have sent the invite to Stewien. I will remove myself as owner after he accepts.

**Comment by vslee** [comment]
> I've got github set up to automatically publish to nuget, now all I need is permission on the nuget package,

I think you also need to have a step where you increment the version number prior to publishing to nuget. Packages on nuget are immutable (like your collections!). Thus, once one for a version number exists there, it can no longer be replaced.

**Comment by stewienj** [comment]
@vslee The version number is now based on the time it was compiled (epoch based), thus the version number will always be bigger than the last time it was compiled. You probably know this, but .NET does this for you if in your AssemblyInfo.cs file you set your assembly version to major.minor.* (for example: 3.0.*). When you build your project the version is auto generated. Which is what I've done.

I've accepted the invitation from @fjch1997, ran the github action, and it successfully published the nuget package. There was an error in the action, it tried to publish symbols for the symbol server for debugging, but failed because there weren't any. I'll try to work out how to generate the symbols.

**Comment by stewienj** [comment]
Got the symbol package working now

**Comment by vslee** [comment]
The nuget worked for me

**Pull request merged**
